# docker-compose.yml

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8080 altflex.wsgi:application
    volumes:
      - .:/app_alternativa
      - static_volume:/app_alternativa/staticfiles
      - media_volume:/app_alternativa/media
    expose:
      - 8080
    environment:
      - PORT=8080
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - DJANGO_SETTINGS_MODULE=altflex.settings
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_server
    volumes:
      - static_volume:/app_alternativa/staticfiles
      - media_volume:/app_alternativa/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  media_volume: